packages:
  - SecureMail-Backend
  - SecureMail-Frontend
  - SecureMail-Ai
  - SecureMail-Malware
  - SecureMail-Flutter

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
